
variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

stages:
    - build
    - test
    - deploy

build-centos-9-stream:
    image: quay.io/centos/centos:stream9
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    stage: build
    before_script:
        - yum -y update
        - yum install -y gcc gcc-c++ make gmp-c++ gmp-devel 
        - yum install -y openssl-devel libcurl-devel file rpm-build cmake
        - cd /tmp
        - curl -LOJ https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/libunistring-devel-0.9.10-15.el9.x86_64.rpm
        - yum install -y ./libunistring*.rpm
        - rm -f ./lib*.rpm
        - cd -
    script:
        - cmake -S. -Bbuild
        - cmake --build build --target all -- -j$(nproc)
    cache:
       key: "centos-${CI_COMMIT_REF_SLUG}"
       paths:
        - build


build-debian-11:
    image: debian:bullseye
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    stage: build
    before_script:
        - apt -y update
        - apt -y install cmake gcc g++
        - apt -y install libgmp-dev libssl-dev 
        - apt -y install libunistring-dev
    script:
        - cmake -S. -Bbuild
        - cmake --build build --target all -- -j$(nproc)
    cache:
       key: "debian-11-${CI_COMMIT_REF_SLUG}"
       paths:
        - build

build-debian-12:
    image: debian:bookworm
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    stage: build
    before_script:
        - apt -y update
        - apt -y install cmake gcc g++
        - apt -y install libcurl4-openssl-dev libssl-dev
        - apt -y install dpkg-dev file libgmp-dev
        - apt -y install libunistring-dev
    script:
        - cmake -S. -Bbuild
        - cmake --build build --target all -- -j$(nproc)
    cache:
       key: "debian-12-${CI_COMMIT_REF_SLUG}"
       paths:
        - build

test-debian-11:
    image: debian:bullseye
    stage: test
    before_script:
        - apt -y update
        - apt -y install libcurl4 libssl1.1
        - apt -y install libgmp10
    script:
        - ldd build/src/test/unittests
        - build/src/test/unittests
    cache:
       key: "debian-11-${CI_COMMIT_REF_SLUG}"
       paths:
        - build

test-debian-12:
    image: debian:bookworm
    stage: test
    before_script:
        - apt -y update
        - apt -y install libcurl4 libssl3
    script:
        - ldd build/src/test/unittests
        - build/src/test/unittests
    cache:
       key: "debian-12-${CI_COMMIT_REF_SLUG}"
       paths:
        - build

test-centos-9-stream:
    image: quay.io/centos/centos:stream9
    stage: test
    script:
        - ldd build/src/test/unittests
        - build/src/test/unittests
    cache:
       key: "centos-${CI_COMMIT_REF_SLUG}"
       paths:
        - build

